### ISSUE TITLE
env vars not resolved

### ISSUE THREAD

**Issue by yentsun** [xshellinc/ini-config#2]
got this in my config.ini:
```ini
...
[default.storageConfig]
name = stat
port = 5432
nolimit = true

[development.storageConfig]
username = $storageConfig_username
password = $storageConfig_password
host = $storageConfig_host
```

and I get this in config object:
```
20|📈 stat |   storageConfig: 
20|📈 stat |    { name: 'stat',
20|📈 stat |      port: '5432',
20|📈 stat |      nolimit: true,
20|📈 stat |      username: '$storageConfig_username',
20|📈 stat |      password: '$storageConfig_password',
20|📈 stat |      host: '$storageConfig_host' },

```

**Comment by yentsun** [comment]
@Teq is there a check for env vars to be uppercase?

**Comment by Teq** [comment]
> @Teq is there a check for env var names to be uppercase?

Yes. Current regex to match placeholders: /^\$([A-Z1-9_]+)$/
Going to change it to: /^\$(\w+)$/

**Comment by Teq** [comment]
@yentsun Changed here: https://github.com/xshellinc/ini-config/releases/tag/v0.1.2

**Comment by yentsun** [comment]
@Teq thanks :) I understand that env vars are usually UPPERCASE, but we do have some legacy vars camelCased. We'll switch to uppercase eventually
