### ISSUE TITLE
'package: require('~/package.json')' in config

### ISSUE THREAD

**Issue by Teq** [xshellinc/ini-config#3]
Old code used to merge config environments: 

```javascript
export default merge(
    {
        environment,
        package: require('~/package.json')
    },
    config.default,
    config[environment]
);
```

Notice `package: require('~/package.json')` here. It is not possible to fill this node from within ini-config package because it runs as a module and has its own package.json.

For now I fill it manually while config being loaded:

```javascript
const configFileName = path.join(__dirname, 'config.ini');
const config = load(configFileName, { options: { environment: process.env.ENV } });
export default merge({ package: require('~/package.json') }, config);
```

But maybe we can just drop it.. As I can see it's only used as a part of log message on application start: https://github.com/xshellinc/isaax-mail-service/blob/develop/src/mail-service.js#L42

**Comment by Teq** [comment]
@yentsun What do you think?

**Comment by yentsun** [comment]
> As I can see it's only used as a part of log message on application start: 

Its also used in `cmd:status` to respond with package info currently running

But its ok, package is probably not a part of configuration so we can ignore it in this module
